#! /bin/bash -e

shift

default_locations=(
	/Volumes/LIFELINE_A
	/Volumes/NO\ NAME/
	/Users/sasha/Library/CloudStorage/GoogleDrive-sasha.friedenberg@gmail.com/My\ Drive/
)

if [[ "${#@}" -eq 0 ]]; then
	locations=("${default_locations[@]}")
else
	locations=("$@")
fi

for outdir in "${locations[@]}"; do
	if ! [[ -d "$outdir" ]]; then
		continue
	fi

	echo "***"
	echo syncing to "$outdir" >&2
	caffeinate -imsd rsync -ruzhP ./.zit/ "$outdir/zit/.zit/"
	echo "***"
done
