#! /bin/bash -e

verb="$1"

ia_writer_print_all_md() (
	dir="$HOME/Library/Mobile Documents/27N4MQEA55~pro~writer/Documents"
	find "$dir" -iname '*.md' -print0
)

make_zettel() (
  file="$1"
  etikett="$2"
  echo ---
  echo "# $(head -n1 "$file")"
  echo "- $etikett"
  echo ---
  echo
  gtail -n+2 "$file"
)

zit_add_today() (
	today="$(date -u +%Y-%m-%d)"
  etikett="zz-inbox-$today"

  for file in "$@"; do
    make_zettel "$file" "$today"
    zit new -edit=false <(make_zettel "$file" "$etikett")
    rm "$file"
  done

  zit organize "$etikett"
)

export -f ia_writer_print_all_md
export -f zit_add_today
export -f make_zettel

case "$verb" in
push)
	echo "Push not implemented" >&2
	exit 1
	;;

pull)
	ia_writer_print_all_md | xargs -0 bash -c 'zit_add_today "$@"' --
	;;

*)
	echo "Unsupported verb: $verb" >&2
	exit 1
	;;
esac
