#! /bin/bash -e

eval `/usr/libexec/path_helper -s`

file="$1"
tacky="$(which tacky)"

echo "Running pandoc..."
./.zit/bin/strip-metadatei "$file" \
  | pandoc --wrap=none --to html -demail \
  | sed 's|<title>-</title>||' \
  | "$tacky" copy \
    -i public.html - \
    -i public.utf8-plain-text <(./.zit/bin/strip-metadatei "$file" | pandoc -dforum --wrap=none)
echo "Copied to pasteboard"
