#! /bin/bash -e

cat_zettel() (
	f="$1"

	if [[ -f "$f" ]]; then
		.zit/bin/strip-metadatei "$f"
	else
		zit cat-objekte -type akte "$f"
	fi
)

shift

run_pandoc() (
 out="$(mktemp).pdf"
 mmdc -i <(cat) -o "$out"
	cat "$out"
)

run_icat() (
	kitty +kitten icat --background white --scale-up
)

for f in "$@"; do
	cat_zettel "$f" |
		run_pandoc |
		run_icat
done
