#! /bin/bash -e

date() (
	command date "+%Y-%m-%d"
)

date_tag() (
	echo "zz-inbox-$(date)"
)

shift

if [[ "${#@}" -gt 0 ]]; then
	zit organize "$@" "$(date_tag)"
else
	zit organize "$(date_tag)"
fi
