#! /bin/bash -e

date() (
	command date "+%Y-%m-%d"
)

date_tag() (
	echo "zz-inbox-$(date)"
)

if ! dir="$(./.zit/bin/chrome_tabs_to_files)"; then
	echo "failed to pull chrome tabs" >&1
	exit 1
fi

#TODO support no tabs
zit new -edit=false -dedupe -etiketten "$inbox_tag" $dir/*
# zit organize -group-by zz-site "$inbox_tag" !toml-bookmark

if ! ./.zit/bin/chrome_close_all; then
	echo "failed to close all chrome tabs" >&1
	exit 1
fi

echo "deleting tabs saved to '$dir'" >&2
rm -r "$dir"
